import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import ExternalSiteCard from "../common/ExternalSiteCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const externalWebsites = [
    {
      name: "Github",
      url: "https://github.com/yui666a",
      imageSrc: "/github.png",
      imageAlt: "github logo",
    },
    {
      name: "Qiita",
      url: "https://qiita.com/yui666a",
      imageSrc: "/qiita.svg",
      imageAlt: "qiita logo",
    },
    {
      name: "Instagram",
      url: "https://instagram.com/yui.ai",
      imageSrc: "/instagram.svg",
      imageAlt: "instagram logo",
    },
  ];

  return (
    <>
      <Head>
        <title>test site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div>相曽結 (AISO, Hitoshi)</div>
          <div>1998年生まれ</div>
          <div>大阪府出身</div>
          <div>長岡技術科学大学 情報・経営システム工学分野 修士1年</div>
          <div>長岡技術科学大学 情報・経営システム工学課程 卒業</div>
          <div>奈良工業高等専門学校 情報工学科 卒業</div>
          <div>PL学園中学校 卒業</div>
        </div>

        <Image
          // className={styles.logo}
          src="/profile.jpg"
          alt="profile image"
          width="100"
          height="100"
          style={{ width: "50%", height: "auto" }}
        />
        <h2>外部サイト</h2>
        <div>
          {externalWebsites.map((website) => (
            <ExternalSiteCard
              key={website.name}
              siteName={website.name}
              siteUrl={website.url}
              siteIcon={website.imageSrc}
              siteIconDescription={website.imageAlt}
            />
          ))}
        </div>
      </main>
    </>
  );
}
